### ISSUE TITLE
4.3节中的错误

### ISSUE THREAD

**Issue by BriFuture** [feiyanke/thinkdsp-cn#1]
![image](https://user-images.githubusercontent.com/7582298/53861348-f5e2f880-401e-11e9-9714-6056054ec8bf.png)

1. 布朗噪声的频谱图的几乎所有的频率成分都在最是低频  =>  都是在低频
2. 为了更清除的显示频谱图  => 清楚

**Comment by feiyanke** [comment]
Thanks, I will fix it later.

**Comment by BriFuture** [comment]
2.3 节“混叠” 中的错误：

![image](https://user-images.githubusercontent.com/7582298/54112332-e4379180-4420-11e9-9bd2-fef3b50a1128.png)

显示了一个1100Hz的三角信号在1KHz采样率下 =>  1KHz采样率应该为 10K采样率。

原文是 10,000 frames per second
